name: ConquestiaSkills
main: com.ultiferrago.conquestiaskills.ConquestiaSkills
version: 0.2
author: Ultiferrago
depend: [SkillAPI]

commands:
  cq:
    description: Only used for bonus xp (so far).

permissions:
  conquestiaskills.admin:
    default: op
    



