name: ConquestiaSkills
main: com.ultiferrago.conquestiaskills.ConquestiaSkills
version: 0.3.2.1
author: Ultiferrago
depend: [SkillAPI]

commands:
  cq:
    description: Plugin Commands, duh!

permissions:
  conquestiaskills.admin:
    default: op
    



